### ISSUE TITLE
请问api的授权这里要填的token，是UserToken表里面存储的Token么

### ISSUE THREAD

**Issue by bosetVSmeier** [oncemi/OnceMi.Framework#1]
你好，请问api的授权这里要填的token，是UserToken表里面存储的Token么

![1](https://user-images.githubusercontent.com/23550179/147845360-d4a6fa40-a50d-43da-a17a-f3e857b0a53b.png)

**Comment by withsalt** [comment]
是的
正确格式应该是：Bearer 【token】

**Comment by bosetVSmeier** [comment]
好的
