### ISSUE TITLE
如果接入自己的SSO

### ISSUE THREAD

**Issue by bosetVSmeier** [oncemi/OnceMi.Framework#2]
你好，请问如果我要使用现有的SSO，如何接入

**Comment by withsalt** [comment]
1. 修改appsettings.xxx.json中IdentityServer配置，设置IsEnabledIdentityServer为true，Url和Audience修改为当前的。
2. 修改OnceMi.Framework.Extension.Authorizations.PermissionAuthorizationHandler中用户认证逻辑。这块可能有点麻烦，我们几乎没有考虑接入现有的SSO，主要是各自开发的SSO用户数据不尽相同，又不可能像微信接入那各自搞一套用户体系。

**Comment by bosetVSmeier** [comment]
感谢回复，搞了一天还没跑通
