### ISSUE TITLE
你好，为什么设置不需要登录拦截不起效果呢

### ISSUE THREAD

**Issue by bosetVSmeier** [oncemi/OnceMi.Framework#3]
![image](https://user-images.githubusercontent.com/23550179/150489007-7a898467-0cf6-4185-9e43-5963b4ceed32.png)
![image](https://user-images.githubusercontent.com/23550179/150489082-ecbc6b9f-655d-49aa-8f67-d1fcf6c50761.png)

我在router.map.js里面配置了一个Demo的邮路，然后在\router\index.js里面设置了不需要登录拦截的路由配置，但是没效果，是还需要设置别的地方么

**Comment by withsalt** [comment]
是否在菜单中添加demo的菜单，并授权？路由是动态取的，没有添加相应的菜单和权限前段拿不到路由。

**Comment by withsalt** [comment]
在router->async->router.async.js文件中添加一个demo，不然找不到路由。其余的路由是登录之后动态获取的。

**Comment by bosetVSmeier** [comment]
![image](https://user-images.githubusercontent.com/23550179/150494739-4a70919d-d7f0-41de-b9e3-25dbd93dd2b8.png)
这里么？我加了。现在我想创建一个页面，然后是不受该系统登录限制的，谁都可以访问的一个公开页面，该怎么做呢？

**Comment by bosetVSmeier** [comment]
可以了

**Comment by bosetVSmeier** [comment]
你好，我新建一个api，后台可以跳过授权认证么，我加了AllowAnonymous还是一直401
![image](https://user-images.githubusercontent.com/23550179/150513858-659a016c-b3b8-4d5e-8bae-0cd1cc570e44.png)

**Comment by withsalt** [comment]
是不是路由不正确？
